language: go
sudo: false
go:
- tip
before_install:
- curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
- dep ensure
- go run main.go --generate_keys
install:
- go get github.com/mattn/goveralls
script:
    - $GOPATH/bin/goveralls -service=travis-ci
    - go test ./... -v
